curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
# install node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
source ~/.bashrc
nvm list-remote
nvm install v14.10.0
