# change package.json for application to work
# "@apollo/client": "~3.4.0",
apt update && apt upgrade
apt install curl -y
# install node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
source ~/.bashrc
nvm list-remote
nvm install v16.20.0
